---
labels:
  author: SouthWinds Tech Ltd
  application: DbMan Command Line Interface
  description: Database Manager command line interface
  architecture: AMD64

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  IMG_REPO: quay.io/artisan
  IMG_NAME: dbman
  BUILD: 1.0.0-${ARTISAN_REF}
  PLUGIN_PREFIX: "dbman-db-"

profiles:
  - name: linux
    default: true
    application: dbman
    type: content/binary
    license: Apache Version 2
    labels:
      platform: linux
    env:
      GOOS: linux
    run:
      - $(build-linux)
    target: bin/linux/dbman

functions:
  - name: build-mac
    description: builds the DbMan CLI for MacOS
    env:
      GOOS: darwin
    run:
      - go build -o bin/darwin/dbman -v

  - name: build-linux
    description: builds the DbMan CLI for the linux platform
    env:
      GOOS: linux
    run:
      - go build -o bin/linux/dbman -v

  - name: swagen
    description: generates/refreshes the OpenAPI specifications for DbMan's HTTP API
    run:
      - swag init -d "./" -g core/handlers.go

  - name: build-image
    run:
      - docker pull registry.access.redhat.com/ubi8/ubi-minimal
      - $(build-linux)
      - art run build-linux ./plugin/pgsql
      - cp ./plugin/pgsql/bin/linux/${PLUGIN_PREFIX}pgsql ./build
      - cp bin/linux/dbman build
      - docker build -t ${IMG_REPO}/${IMG_NAME}:${BUILD} ./build
      - docker tag ${IMG_REPO}/${IMG_NAME}:${BUILD} ${IMG_REPO}/${IMG_NAME}:latest
      - docker login quay.io -u artisan -p ${IMG_REG_PWD}
      - docker push ${IMG_REPO}/${IMG_NAME}:${BUILD}
      - docker push ${IMG_REPO}/${IMG_NAME}:latest
...
